name: AstrowayCustomer
description: The Astrology app

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 2.2.0

environment:
  sdk: ">=3.2.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  #UI DESIGN
  font_awesome_flutter: ^10.7.0
  # skeletonizer: ^1.4.3 # Removed due to Canvas API incompatibility with Flutter 3.35.3
  cupertino_icons: ^1.0.6
  material_design_icons_flutter: ^7.0.7296
  flutter_rating_bar: ^4.0.1
  flutter_html: ^3.0.0-alpha.5
  bubble_tab_indicator: ^0.1.6
  flutter_image_slideshow: ^0.1.6
  date_format: 2.0.7
  video_player: ^2.9.1
  percent_indicator: ^4.2.3
  photo_view: ^0.14.0
  # custom_clippers: ^2.0.0 # Removed due to Canvas API incompatibility with Flutter 3.35.3
  url_launcher: ^6.3.1

  #MULTI-LANGUAGE
  easy_localization: ^3.0.5

  #WEBVIEW
  flutter_inappwebview: ^6.0.0

  #TOAST MESSAGE
  fluttertoast: ^8.1.1

  #AGORA
  agora_rtm: ^2.2.0
  agora_rtc_engine: ^6.5.0

  #SYSTEM PERMISSION
  permission_handler: ^11.4.0
  path_provider: ^2.1.5

  #DEVICE INFO
  device_info_plus: ^11.3.3

  #CONNECTIVITY
  connectivity_plus: ^6.1.3
  http: ^1.2.2

  #LOCATION
  geocoding: ^3.0.0
  flutter_google_places_sdk: ^0.3.7

  #PDF VIEWER
  syncfusion_flutter_pdfviewer: ^29.1.33

  #REDIRECT
  store_redirect: ^2.0.1

  #SCORE
  syncfusion_flutter_gauges: ^29.1.33

  #PLATFORM INFO
  package_info_plus: ^8.0.0
  flutter_countdown_timer: ^4.1.0

  #DATE TIME PICKER
  flutter_holo_date_picker: ^1.1.0
  flutter_time_picker_spinner: ^2.0.0

  #STATE MANAGEMENT
  get: ^4.6.6

  #FIREBASE
  flutter_local_notifications: ^17.2.1+2
  cloud_firestore: ^5.6.5
  googleapis_auth: ^1.6.0
  firebase_auth: ^5.5.1
  firebase_core: ^3.12.1
  firebase_messaging: ^15.2.4
  firebase_storage: ^12.4.4

  #LOCAL STORAGE
  shared_preferences: ^2.3.1

  intl_phone_number_input: ^0.7.4

  #IMAGE
  image_picker: ^1.1.2
  image_cropper: ^9.0.0
  cached_network_image: ^3.4.1

  marquee: ^2.2.3

  #Audioplayer
  audioplayers: ^6.4.0

  #YOUTUBE PLAYER
  youtube_player_flutter: ^9.0.0

  #PDF
  pdf: ^3.11.0
  share_plus: ^10.0.0

  uuid: ^4.4.0

  draggable_widget: ^2.0.0
  responsive_sizer: ^3.3.0+1

  intl: any

  story_view: ^0.16.5
  swipe_to: ^1.0.6
  file_picker: ^8.0.0+1
  open_file: ^3.3.2
  lecle_yoyo_player: ^0.0.8
  otpless_flutter: ^2.1.4
  pin_input_text_field: ^4.5.1
  flutter_callkit_incoming: ^2.0.4+1
  get_storage: ^2.1.1
  logger: ^2.4.0
  flutter_svg: ^2.0.10+1
  timelines_plus: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/translations/
    - assets/ringtone.mp3
    - lib/utils/noti_service.json

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-Thin.ttf
        - asset: assets/fonts/Poppins-ExtraBold.ttf
        - asset: assets/fonts/Poppins-ExtraLight.ttf
        - asset: assets/fonts/Poppins-Light.ttf
